### PR TITLE
rolled back std to 0.126.0

### PR DESCRIPTION
**Pull request by retog**
This is to avoid commit https://github.com/denoland/deno_std/commit/5e8adcbfc4d1f752d06e53996b661ac4258e4886 as Property 'reason' does not exist on type 'AbortSignal', the breaking change in std was introduced with https://github.com/denoland/deno_std/pull/1939.

### CODE REVIEW

**Comment by retog** [comment]
obsolete.
